apiVersion: v1
kind: Service
metadata:
  name: {{ include "predict.fullname" . }}
  labels:
    {{- include "predict.labels" . | nindent 4 }}
  annotations:
    {{ tpl .Values.annotations . | nindent 4 | trim }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - port: {{ $value.port }}
      targetPort: {{ $key }}
      protocol: {{ $value.protocol }}
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "predict.selectorLabels" . | nindent 4 }}
