{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "predict.serviceAccountName" . }}
  labels:
    {{- include "predict.labels" . | nindent 4 }}
  {{- if and .Values.aws.enabled .Values.aws.role }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.role }}
  {{- else }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end -}}
