prometheus:
    url: http://172.31.83.51
    port: 9090
    path: ""
metricsRelistInterval: 1m
rules:
  default: false
  custom:
  -
    seriesQuery: 'nginx_vts_server_requests_total'
    seriesFilters: []
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: "^(.*)_total"
      as: "${1}_per_second"
    metricsQuery: (sum(rate(<<.Series>>{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>))
  -
    seriesQuery: 'nps_server_perfermance_curr_qps'
    seriesFilters: []
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: "^(.*)_qps"
      as: "${1}_per_second"
    metricsQuery: (avg(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>))
  -
    seriesQuery: 'DCGM_FI_DEV_GPU_UTIL'
    seriesFilters: []
    resources:
      overrides:
        exported_namespace:
          resource: namespace
        exported_pod:
          resource: pod
    name:
      matches: "^(.*)_UTIL"
      as: "${1}_per_second"
    metricsQuery: (avg(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>))
